"""sync subscription lifecycle and history

Revision ID: 5c13bad79a18
Revises: 
Create Date: 2026-08-08 18:31:53.808141

"""

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


from sqlalchemy.dialects import postgresql



# ==========================================================
# Revision Identifiers
# ==========================================================

revision: str = '5c13bad79a18'

down_revision: Union[str, Sequence[str], None] = None

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None



# ==========================================================
# Upgrade Migration
# ==========================================================

def upgrade() -> None:

    """
    Apply database changes.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_cycles')
    op.alter_column('customers', 'company_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('customers', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.add_column('invoices', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint('uq_invoice_number', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.drop_constraint('invoices_subscription_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invoices', 'invoice_date')
    op.add_column('payment_retries', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('payment_retries', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('payment_retries', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payment_retries', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('payment_retries', 'retry_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('payment_retries', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.create_index(op.f('ix_payment_retries_payment_id'), 'payment_retries', ['payment_id'], unique=False)
    op.drop_constraint('payment_retries_payment_id_fkey', 'payment_retries', type_='foreignkey')
    op.create_foreign_key(None, 'payment_retries', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.drop_constraint('payments_invoice_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('plans', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('plans', 'billing_cycle',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_subscription_history_action'), 'subscription_history', ['action'], unique=False)
    op.create_index(op.f('ix_subscription_history_id'), 'subscription_history', ['id'], unique=False)
    op.add_column('subscriptions', sa.Column('lifecycle_metadata', sa.JSON(), nullable=True))
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_subscriptions_cancel_at_period_end'), 'subscriptions', ['cancel_at_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_current_period_end'), 'subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscriptions_current_period_start'), 'subscriptions', ['current_period_start'], unique=False)
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_billing_date'), 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.drop_constraint('subscriptions_plan_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_customer_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'updated_at')
    # ### end Alembic commands ###



# ==========================================================
# Downgrade Migration
# ==========================================================

def downgrade() -> None:

    """
    Reverse database changes.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_customer_id_fkey', 'subscriptions', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key('subscriptions_plan_id_fkey', 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_current_period_end'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_cancel_at_period_end'), table_name='subscriptions')
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'monthly'::character varying"),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('subscriptions', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
    op.drop_column('subscriptions', 'lifecycle_metadata')
    op.drop_index(op.f('ix_subscription_history_id'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_action'), table_name='subscription_history')
    op.alter_column('subscription_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('plans', 'billing_cycle',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('plans', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('plans', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_invoice_id_fkey', 'payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'transaction_id')
    op.drop_constraint(None, 'payment_retries', type_='foreignkey')
    op.create_foreign_key('payment_retries_payment_id_fkey', 'payment_retries', 'payments', ['payment_id'], ['id'])
    op.drop_index(op.f('ix_payment_retries_payment_id'), table_name='payment_retries')
    op.alter_column('payment_retries', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('payment_retries', 'retry_date',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('payment_retries', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('payment_retries', 'payment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payment_retries', 'created_at')
    op.drop_column('payment_retries', 'error_message')
    op.add_column('invoices', sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_subscription_id_fkey', 'invoices', 'subscriptions', ['subscription_id'], ['id'])
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.create_unique_constraint('uq_invoice_number', 'invoices', ['invoice_number'])
    op.alter_column('invoices', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoices', 'subscription_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'customer_id')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('customers', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('customers', 'contact_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'company_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.create_table('billing_cycles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('billing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='billing_cycles_subscription_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='billing_cycles_pkey')
    )
    # ### end Alembic commands ###
    